### ISSUE TITLE
Tarefa 01 - Consultas Aninhadas

### ISSUE THREAD

**Issue by br-adriel** [br-adriel/banco-dados-2#1]

**Comment by tacianosilva** [comment]
@br-adriel tarefa corrigida!

(1,0) Q1 - Criar tarefa - Correta!
(1,0) Q2 - Criar tarefa01-create.sql - Correta!
(0,5) Q3 - Criar tarefa01-inserts.sql - Ok, fez dentro do tarefa01-create.sql.
(0,0) Q4 - Criar tarefa01.md - Não fez!
(5,0) Q5 - Resolver 5 questões SQL:
    Q5.1 - questao01.md
    Q5.2 - questao04.md
    Q5.3 - questao07.md
    Q5.4 - questao10.md
    Q5.5 - questao13.md
(1,0) - Fez vários commits com identificação da tarefa.
